### ISSUE TITLE
Compile error during gulp.

### ISSUE THREAD

**Issue by w9** [cancerregulome/RegulomeExplorer#21]
I downloaded the git repository and ran the following commands:

```
npm install
bower install
gulp
```

The `npm` and `bower` installation appeared to be successful. However, when I ran the `gulp` command, a `[Compile Error]` came up saying:

```
[Compile Error] ./RegulomeExplorer/app/scripts/app.js:1:8: Semi-colon expected
```

Looking into the `app.js` mentioned, I found that the first few lines looks like this:

```
module React from 'react';
import {
    GridView
}
```

I don't quite understand why the compiler wants a semi-colon before the word `React`. I double-checked that the package `react` was installed (there's an item in the `package.json` file, and I also installed it manually by `npm install react`).

The page that popped up after finishing compiling is nothing but blank. When I looked into the console, there was an error saying:

```
TypeError: $traceurRuntime.assertObject is not a function
```

**Comment by mictadlo** [comment]
Hi, I have a different error:
```
sudo docker run -i -t -v ~/projects/RegulomeExplorer--Deprecated:/data/ digitallyseamless/nodejs-bower-grunt:0.10 /bin/bash
npm install
bower install
npm install --global gulp-cli
npm install gulp -D
gulp

Error: Cannot find module 'imagemin-jpegtran'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/data/node_modules/gulp-imagemin/node_modules/imagemin/index.js:171:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
Any idea what am I missing?

Thank you in advance.

Michal
